In [8]:
#starting point 
import numpy as np 
np .__version__

'2.0.2'

In [16]:
#matrixname np.values_Range.change the Dimension of array 
A = np.arange(12).reshape(4,3)
B = np.arange(1,7).reshape(3,2)
print(A)
print(B)
# np.sum(A,axis=0) just a quick revision of summation using axis 
# np.sum(A,axis=1) sameways can do for matrix B

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[1 2]
 [3 4]
 [5 6]]


In [17]:

c1 = np.matmul(A,B[:,0]) #multiplication of all  rows of A with the first column of B
c2 = np.matmul(A,B[:,1]) #multiplication of all rows of A with the second column of B
C = np.concatenate((c1.reshape(-1,1),c2.reshape(-1,1)),axis=1)
C

array([[ 13,  16],
       [ 40,  52],
       [ 67,  88],
       [ 94, 124]])

In [23]:
# Another method of doing the above code
# import numpy as np

# A = np.arange(12).reshape(3,4)
# B = np.arange(1,7).reshape(3,2)

# # Correct approach: slice each row of A and multiply with corresponding element of B
# c1 = np.sum(A * B[:, 0].reshape(-1, 1), axis=1)  # Broadcasting to multiply A's rows with B[:,0]
# c2 = np.sum(A * B[:, 1].reshape(-1, 1), axis=1)  # Broadcasting to multiply A's rows with B[:,1]

# C = np.concatenate((c1, c2.reshape(-1,), axis=1)
# print(C)


In [32]:
# PSEUDO INVERSE METHOD 
#getting Determinant to know whether the inverse exists or not
D = np.array([[1,2],[2,4]])

Det_D = np.linalg.det(D)

D.T # D.transpose() 'also works' 

P_inverse = np.linalg.pinv(D)
print(P_inverse)

[[0.04 0.08]
 [0.08 0.16]]


In [35]:
# Inverse using numpy a standard example
M = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
Minv = np.linalg.inv(M)
Result = np.matmul(M,Minv)
print(Result)


[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16 -2.22044605e-16  1.00000000e+00]]
